routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Frontend Routes
|--------------------------------------------------------------------------
| Define the routes for your Frontend pages here
|
*/

Route::get('/', [
    'as' => 'home', 'uses' => 'FrontendController@home'
]);

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
| Route group for Backend prefixed with "admin".
| To Enable Authentication just remove the comment from Admin Middleware
|
*/

Route::group([
    'prefix' => 'admin',
    'middleware' => 'admin'
], function(){

    // Dashboard
    //----------------------------------
    Route::get('/', [
        'as' => 'admin.dashboard', 'uses' => 'DashboardController@index'
    ]);
    Route::resource('users', 'UsersController');
    Route::resource('roles', 'RolesController');
    // Settings
    //----------------------------------
    Route::group(['prefix' => 'settings'], function(){

        Route::get('/social', [
            'as' => 'admin.settings.index', 'uses' => 'SettingsController@index'
        ]);

        Route::post('/social', [
            'as' => 'admin.settings.social', 'uses' => 'SettingsController@postSocial'
        ]);

        Route::group(['prefix' => 'mail'], function(){

            Route::get('/', [
                'as' => 'admin.settings.mail.index', 'uses' => 'SettingsController@mail'
            ]);

            Route::post('/', [
                'as' => 'admin.settings.mail.post', 'uses' => 'SettingsController@postMail'
            ]);

            Route::post('/send-test-email', [
                'as' => 'admin.settings.mail.send', 'uses' => 'SettingsController@sendTestMail'
            ]);
        });

    });
});

/*
|--------------------------------------------------------------------------
| Guest Routes
|--------------------------------------------------------------------------
| Guest routes cannot be accessed if the user is already logged in.
| He will be redirected to '/" if he's logged in.
|
*/

Route::group(['middleware' => ['guest']], function(){

    Route::get('login', [
        'as' => 'login', 'uses' => 'AuthController@login'
    ]);

    Route::get('register', [
        'as' => 'register', 'uses' => 'AuthController@register'
    ]);

    Route::post('login', [
        'as' => 'login.post', 'uses' => 'AuthController@postLogin'
    ]);

    Route::get('forgot-password', [
        'as' => 'forgot-password.index', 'uses' => 'ForgotPasswordController@getEmail'
    ]);

    Route::post('/forgot-password', [
        'as' => 'send-reset-link', 'uses' => 'ForgotPasswordController@postEmail'
    ]);

    Route::get('/password/reset/{token}', [
        'as' => 'password.reset', 'uses' => 'ForgotPasswordController@GetReset'
    ]);

    Route::post('/password/reset', [
        'as' => 'reset.password.post', 'uses' => 'ForgotPasswordController@postReset'
    ]);

    Route::get('auth/{provider}', 'AuthController@redirectToProvider');

    Route::get('auth/{provider}/callback', 'AuthController@handleProviderCallback');
});

Route::get('logout', [
    'as' => 'logout', 'uses' => 'AuthController@logout'
]);

Route::get('install', [
    'as' => 'logout', 'uses' => 'AuthController@logout'
]);

app/Http/Controllers/RolesController.php
<?php
namespace Laraspace\Http\Controllers;

use Illuminate\Http\Request;
use Laraspace\Rol;

use DB;

class RolesController extends Controller
{
    public function index()
    {
        $roles = Rol::all();

        return view('admin.roles.index')->with('roles', $roles);
    }

    public function create()
    {
        return view('admin.roles.create');
    }

    public function store(Request $rq)
    {
        try{
            DB::beginTransaction();
            $rol = new Rol();
            $rol->nombre = $rq->nombre;
            $rol->save();
            flash()->success('Rol creado exitosamente');
            DB::commit();
            return redirect()->route('roles.index');
        }catch(\Exception $e){
            DB::rollback();
            dd($e);
            flash()->warning('Error al intentar crear rol');
            return redirect()->route('roles.create');
        }
    }

    public function edit(Rol $role)
    {
        return view('admin.roles.edit', compact('role'));
    }

    public function update(Request $rq, Rol $role)
    {
        try{
            DB::beginTransaction();
            $role->nombre = $rq->nombre;
            $role->save();
            flash()->success('Rol actualizado exitosamente');
            DB::commit();
            return redirect()->route('roles.index');
        }catch(\Exception $e){
            DB::rollback();
            flash()->warning('Error al intentar actualizar rol');
            return redirect()->route('roles.edit', $role);
        }
    }

    public function destroy($id)
    {
        $rol = Rol::findOrFail($id);
        $rol->delete();
        flash()->success('Rol Deleted');

        return redirect()->back();
    }
}

resources/views/admin/roles/create.blade.php
@extends('admin.layouts.layout-basic')

@section('content')
    <div class="main-content">
        <div class="page-header">
            <h3 class="page-title">Roles</h3>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{route('roles.index')}}">Roles</a></li>
                <li class="breadcrumb-item active">Create</li>
            </ol>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h6>Crear Rol</h6>
                    </div>
                    <form action="{{ route('roles.store') }}" method="post" id="formulario">
                        @csrf
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group row">
                                        <label for="nombre" class="col-form-label col-sm-3">Nombre</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="nombre" placeholder="Ingrese el nombre" required>
                                        </div>
                                    </div>
                                </div>
                            </div>                        
                        </div>
                        <div class="card-footer">
                            <a href="{{ route('roles.index') }}" class="btn btn-secondary btn-pressable">Volver</a>
                            <button type="submit" class="btn btn-success btn-pressable">Crear</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@stop

resources/views/admin/roles/edit.blade.php
@extends('admin.layouts.layout-basic')

@section('content')
    <div class="main-content">
        <div class="page-header">
            <h3 class="page-title">Roles</h3>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{route('roles.index')}}">Roles</a></li>
                <li class="breadcrumb-item active">Edit</li>
            </ol>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h6>Editar Rol</h6>
                    </div>
                    <form action="{{ route('roles.update', $role) }}" method="post" id="formulario">
                        @method('patch')
                        @csrf
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group row">
                                        <label for="nombre" class="col-form-label col-sm-3">Nombre</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="nombre" placeholder="Ingrese el nombre" value="{{ $role->nombre }}" required>
                                        </div>
                                    </div>
                                </div>
                            </div>                        
                        </div>
                        <div class="card-footer">
                            <a href="{{ route('roles.index') }}" class="btn btn-secondary btn-pressable">Volver</a>
                            <button type="submit" class="btn btn-success btn-pressable">Actualizar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@stop

resources/views/admin/roles/index.blade.php
@extends('admin.layouts.layout-basic')

@section('scripts')
<script>
    $(document).ready(function () {
        
        $('#roles-datatable').DataTable({
            responsive: true
        });
        
        $('[data-confirmation="notie"]').on('click', function (e) {
            e.preventDefault();
            
            var reg = $(this);

            notie.confirm({
                text: 'Esta seguro de eliminar?',
                submitText: 'Si', 
                cancelText: 'Cancelar',
                submitCallback: function () {
                    deleteReg(reg);
                }
            });
            return false
        });

        function deleteReg (reg) {
            console.log(reg);
            var url = reg.attr('href');
            var token = reg.data('token');
            console.log(url);
            $.ajax({
                type: 'POST',
                data: {_method: 'delete', _token: token},
                url: url,
                success: function (data) {
                    toastr['success']('Rol Deleted', 'Success');
                    $(reg).closest('tr').remove();
                },
                error: function (data) {
                    toastr['error']('There was an error', 'Error')
                }
            });
        }  
    });  
</script>
@stop

@section('content')
    <div class="main-content">
        <div class="page-header">
            <h3 class="page-title">Roles</h3>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{route('users.index')}}">Users</a></li>
                <li class="breadcrumb-item active">Roles</li>
            </ol>
            <div class="page-actions">
                <a href="{{ route('roles.create') }}" class="btn btn-primary"><i class="icon-fa icon-fa-plus"></i> Nuevo Rol</a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h6>Roles</h6>

                        <div class="card-actions">

                        </div>
                    </div>
                    <div class="card-body">
                        <table id="users-datatable" class="table table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                                @foreach($roles as $rol)
                                <tr>
                                    <td>{{$rol->nombre}}</td>
                                    <td>
                                        <a href="{{route('roles.edit',$rol)}}" class="btn btn-default btn-sm"><i class="icon-fa icon-fa-edit"></i> Edit</a>
                                        <a href="{{route('roles.destroy',$rol->id)}}" class="btn btn-default btn-sm" data-token="{{csrf_token()}}" data-confirmation="notie"> <i class="icon-fa icon-fa-trash"></i> Delete</a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop