routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Frontend Routes
|--------------------------------------------------------------------------
| Define the routes for your Frontend pages here
|
*/

Route::get('/', [
    'as' => 'home', 'uses' => 'FrontendController@home'
]);

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
| Route group for Backend prefixed with "admin".
| To Enable Authentication just remove the comment from Admin Middleware
|
*/

Route::group([
    'prefix' => 'admin',
    'middleware' => 'admin'
], function(){

    // Dashboard
    //----------------------------------
    Route::get('/', [
        'as' => 'admin.dashboard', 'uses' => 'DashboardController@index'
    ]);
    Route::resource('users', 'UsersController');
    Route::resource('roles', 'RolesController');
    // Settings
    //----------------------------------
    Route::group(['prefix' => 'settings'], function(){

        Route::get('/social', [
            'as' => 'admin.settings.index', 'uses' => 'SettingsController@index'
        ]);

        Route::post('/social', [
            'as' => 'admin.settings.social', 'uses' => 'SettingsController@postSocial'
        ]);

        Route::group(['prefix' => 'mail'], function(){

            Route::get('/', [
                'as' => 'admin.settings.mail.index', 'uses' => 'SettingsController@mail'
            ]);

            Route::post('/', [
                'as' => 'admin.settings.mail.post', 'uses' => 'SettingsController@postMail'
            ]);

            Route::post('/send-test-email', [
                'as' => 'admin.settings.mail.send', 'uses' => 'SettingsController@sendTestMail'
            ]);
        });

    });
});

/*
|--------------------------------------------------------------------------
| Guest Routes
|--------------------------------------------------------------------------
| Guest routes cannot be accessed if the user is already logged in.
| He will be redirected to '/" if he's logged in.
|
*/

Route::group(['middleware' => ['guest']], function(){

    Route::get('login', [
        'as' => 'login', 'uses' => 'AuthController@login'
    ]);

    Route::get('register', [
        'as' => 'register', 'uses' => 'AuthController@register'
    ]);

    Route::post('login', [
        'as' => 'login.post', 'uses' => 'AuthController@postLogin'
    ]);

    Route::get('forgot-password', [
        'as' => 'forgot-password.index', 'uses' => 'ForgotPasswordController@getEmail'
    ]);

    Route::post('/forgot-password', [
        'as' => 'send-reset-link', 'uses' => 'ForgotPasswordController@postEmail'
    ]);

    Route::get('/password/reset/{token}', [
        'as' => 'password.reset', 'uses' => 'ForgotPasswordController@GetReset'
    ]);

    Route::post('/password/reset', [
        'as' => 'reset.password.post', 'uses' => 'ForgotPasswordController@postReset'
    ]);

    Route::get('auth/{provider}', 'AuthController@redirectToProvider');

    Route::get('auth/{provider}/callback', 'AuthController@handleProviderCallback');
});

Route::get('logout', [
    'as' => 'logout', 'uses' => 'AuthController@logout'
]);

Route::get('install', [
    'as' => 'logout', 'uses' => 'AuthController@logout'
]);

app/User.php
<?php
namespace Laraspace;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'facebook_id', 'google_id', 'github_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function isAdmin()
    {
        return ($this->rol_id == '1');
    }

    public function rol()
    {
        return $this->belongsTo('Laraspace\Rol', 'rol_id', 'id');
    }

    public static function login($request)
    {
        $remember = $request->remember;
        $email = $request->email;
        $password = $request->password;
        return (\Auth::attempt(['email' => $email, 'password' => $password], $remember));
    }
}

app/Http/Controllers/UsersController.php
<?php
namespace Laraspace\Http\Controllers;

use Illuminate\Http\Request;
use Laraspace\User;
use Laraspace\Rol;

use DB;

class UsersController extends Controller
{
    public function index()
    {
        $users = User::all();

        return view('admin.users.index')->with('users', $users);
    }

    public function create()
    {
        $roles = Rol::all();
        return view('admin.users.create', compact('roles'));
    }

    public function store(Request $rq)
    {
        try{
            DB::beginTransaction();
            $user = new User();
            $user->name = $rq->nombre;
            $user->rol_id = $rq->rol;
            $user->email = $rq->email;
            $user->password = bcrypt($rq->passw);
            $user->save();
            flash()->success('Usuario creado exitosamente');
            DB::commit();
            return redirect()->route('users.index');
        }catch(\Exception $e){
            DB::rollback();
            flash()->warning('Error al intentar crear usuario');
            return redirect()->route('users.create');
        }
    }

    public function edit(User $user)
    {
        $roles = Rol::all();
        return view('admin.users.edit', compact('user', 'roles'));
    }

    public function update(Request $rq, User $user)
    {
        try{
            DB::beginTransaction();
            $user->name = $rq->nombre;
            $user->rol_id = $rq->rol;
            $user->email = $rq->email;
            $user->save();
            flash()->success('Usuario actualizado exitosamente');
            DB::commit();
            return redirect()->route('users.index');
        }catch(\Exception $e){
            DB::rollback();
            flash()->warning('Error al intentar actualizar usuario');
            return redirect()->route('users.edit', $user);
        }
    }

    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();
        flash()->success('User Deleted');

        return redirect()->back();
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.layout-basic')

@section('content')
    <div class="main-content">
        <div class="page-header">
            <h3 class="page-title">Users</h3>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{route('users.index')}}">Users</a></li>
                <li class="breadcrumb-item active">Create</li>
            </ol>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h6>Crear Usuario</h6>
                    </div>
                    <form action="{{ route('users.store') }}" method="post" id="formulario">
                        @csrf
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group row">
                                        <label for="nombre" class="col-form-label col-sm-3">Nombre</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="nombre" placeholder="Ingrese el nombre" required>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group row">
                                        <label for="rol" class="col-form-label col-sm-3">Rol</label>
                                        <div class="col-sm-9">
                                            <select name="rol" class="form-control ls-select2" required>
                                                <option value="">Seleccione una opción</option>
                                                @foreach($roles as $rol)
                                                <option value="{{ $rol->id }}">{{ $rol->nombre }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group row">
                                        <label for="email" class="col-form-label col-sm-3">Email</label>
                                        <div class="col-sm-9">
                                            <input type="email" class="form-control" name="email" placeholder="Ingrese el correo electrónico" required>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group row">
                                        <label for="passw" class="col-form-label col-sm-3">Password</label>
                                        <div class="col-sm-9">
                                            <input type="password" class="form-control" name="passw" placeholder="Ingrese contraseña" required>
                                        </div>
                                    </div>
                                </div>
                            </div>                        
                        </div>
                        <div class="card-footer">
                            <a href="{{ route('users.index') }}" class="btn btn-secondary btn-pressable">Volver</a>
                            <button type="submit" class="btn btn-success btn-pressable">Crear</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@stop

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.layout-basic')

@section('content')
    <div class="main-content">
        <div class="page-header">
            <h3 class="page-title">Users</h3>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{route('users.index')}}">Users</a></li>
                <li class="breadcrumb-item active">Edit</li>
            </ol>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h6>Editar Usuario</h6>
                    </div>
                    <form action="{{ route('users.update', $user->id) }}" method="POST">
                        @method('patch')
                        @csrf
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group row">
                                        <label for="nombre" class="col-form-label col-sm-3">Nombre</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="nombre" placeholder="Ingrese el nombre" value="{{ $user->name }}" required>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group row">
                                        <label for="rol" class="col-form-label col-sm-3">Rol</label>
                                        <div class="col-sm-9">
                                            <select name="rol" class="form-control ls-select2" required>
                                                <option value="">Seleccione una opción</option>
                                                @foreach($roles as $rol)
                                                    @if($user->rol_id == $rol->id)
                                                        <option value="{{ $rol->id }}" selected>{{ $rol->nombre }}</option>
                                                    @else
                                                        <option value="{{ $rol->id }}">{{ $rol->nombre }}</option>
                                                    @endif
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group row">
                                        <label for="email" class="col-form-label col-sm-3">Email</label>
                                        <div class="col-sm-9">
                                            <input type="email" class="form-control" name="email" placeholder="Ingrese el correo electrónico" value="{{ $user->email }}" required>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>                        
                        </div>
                        <div class="card-footer">
                            <a href="{{ route('users.index') }}" class="btn btn-secondary btn-pressable">Volver</a>
                            <button type="submit" class="btn btn-success btn-pressable">Actualizar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@stop

resources/views/admin/users/index.blade.php
@extends('admin.layouts.layout-basic')

@section('scripts')
<script>
    $(document).ready(function () {
        
        $('#users-datatable').DataTable({
            responsive: true
        });
        
        $('[data-confirmation="notie"]').on('click', function (e) {
            e.preventDefault();
            
            var reg = $(this);

            notie.confirm({
                text: 'Esta seguro de eliminar?',
                submitText: 'Si', 
                cancelText: 'Cancelar',
                submitCallback: function () {
                    deleteUser(reg);
                }
            });
            return false
        });

        function deleteUser (reg) {
            console.log(reg);
            var url = reg.attr('href');
            var token = reg.data('token');
            console.log(url);
            $.ajax({
                type: 'POST',
                data: {_method: 'delete', _token: token},
                url: url,
                success: function (data) {
                    toastr['success']('User Deleted', 'Success');
                    $(reg).closest('tr').remove();
                },
                error: function (data) {
                    toastr['error']('There was an error', 'Error')
                }
            });
        }  
    });  
</script>
@stop

@section('content')
    <div class="main-content">
        <div class="page-header">
            <h3 class="page-title">Users</h3>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{route('users.index')}}">Users</a></li>
                <li class="breadcrumb-item active">Users</li>
            </ol>
            <div class="page-actions">
                <a href="{{ route('users.create') }}" class="btn btn-primary"><i class="icon-fa icon-fa-plus"></i> Nuevo usuario</a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h6>All Users</h6>

                        <div class="card-actions">

                        </div>
                    </div>
                    <div class="card-body">
                        <table id="users-datatable" class="table table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Role</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                                @foreach($users as $user)
                                <tr>
                                    <td>{{$user->name}}</td>
                                    <td>{{$user->email}}</td>
                                    <td>{{$user->rol->nombre}}</td>
                                    <td>
                                        <a href="{{route('users.edit',$user)}}" class="btn btn-default btn-sm"><i class="icon-fa icon-fa-edit"></i> Edit</a>
                                        <a href="{{route('users.destroy',$user->id)}}" class="btn btn-default btn-sm" data-token="{{csrf_token()}}" data-confirmation="notie"> <i class="icon-fa icon-fa-trash"></i> Delete</a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop